apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoice-app
  template:
    metadata:
      labels:
        app: invoice-app
    spec:
      containers:
        - name: invoice-container
          image: sachin868/smart-invoice-generator:latest
          ports:
            - containerPort: 3000 # change if your app runs on another port
          env:
            - name: NODE_ENV
              value: "production"
          # Add other env vars or volume mounts if needed
