apiVersion: v1
kind: Service
metadata:
  name: invoice-service
spec:
  selector:
    app: invoice-app
  type: LoadBalancer  # or NodePort if you don't have a cloud LB
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
